"""Parity gap of the centrosymmetric crystal classes, computed numerically.

For a centrosymmetric point group ``G = G+ ⊔ I·G+`` and an odd-rank polar tensor space ``V``,
inversion acts as ``-1`` so ``V^G = 0`` and the parity gap reduces to ``dim V^{G+}``: the tensor
freedom the proper rotations permit and inversion removes. Invariant dimensions are the trace of
the group-averaging projector (character formula), so the result is exact up to rounding.

Rank 1 is the polarization vector; rank 3 is the piezoelectric tensor restricted to the
18-dimensional subspace symmetric in its two strain indices.
"""

from __future__ import annotations

import csv
import itertools
from dataclasses import dataclass
from pathlib import Path

import numpy as np

_TOL = 1e-9


def _rz(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[c, -s, 0.0], [s, c, 0.0], [0.0, 0.0, 1.0]])


def _rx(theta: float) -> np.ndarray:
    c, s = np.cos(theta), np.sin(theta)
    return np.array([[1.0, 0.0, 0.0], [0.0, c, -s], [0.0, s, c]])


_C3_111 = np.array([[0.0, 0.0, 1.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])

# Generators of each proper subgroup G+ (standard crystallographic settings).
PROPER_GENERATORS: dict[str, tuple[np.ndarray, ...]] = {
    "1": (),
    "2": (_rz(np.pi),),
    "222": (_rz(np.pi), _rx(np.pi)),
    "4": (_rz(np.pi / 2),),
    "422": (_rz(np.pi / 2), _rx(np.pi)),
    "3": (_rz(2 * np.pi / 3),),
    "32": (_rz(2 * np.pi / 3), _rx(np.pi)),
    "6": (_rz(np.pi / 3),),
    "622": (_rz(np.pi / 3), _rx(np.pi)),
    "23": (_rz(np.pi), _C3_111),
    "432": (_rz(np.pi / 2), _C3_111),
}


@dataclass(frozen=True)
class CentrosymmetricClass:
    """One of the eleven centrosymmetric (Laue) crystal classes."""

    point_group: str
    proper_subgroup: str
    crystal_system: str


CENTROSYMMETRIC_CLASSES: tuple[CentrosymmetricClass, ...] = (
    CentrosymmetricClass("-1", "1", "triclinic"),
    CentrosymmetricClass("2/m", "2", "monoclinic"),
    CentrosymmetricClass("mmm", "222", "orthorhombic"),
    CentrosymmetricClass("4/m", "4", "tetragonal"),
    CentrosymmetricClass("4/mmm", "422", "tetragonal"),
    CentrosymmetricClass("-3", "3", "trigonal"),
    CentrosymmetricClass("-3m", "32", "trigonal"),
    CentrosymmetricClass("6/m", "6", "hexagonal"),
    CentrosymmetricClass("6/mmm", "622", "hexagonal"),
    CentrosymmetricClass("m-3", "23", "cubic"),
    CentrosymmetricClass("m-3m", "432", "cubic"),
)


def close_group(generators: tuple[np.ndarray, ...]) -> list[np.ndarray]:
    """All elements of the finite matrix group generated by ``generators``."""
    group = [np.eye(3)]
    frontier = list(group)
    while frontier:
        new = []
        for a in frontier:
            for g in generators:
                m = a @ g
                if not any(np.allclose(m, x, atol=_TOL) for x in group):
                    group.append(m)
                    new.append(m)
        frontier = new
    return group


def _strain_symmetric_projector() -> np.ndarray:
    """Projector onto rank-3 tensors symmetric in their last two indices (dimension 18)."""
    p = np.zeros((27, 27))
    for i, j, k in itertools.product(range(3), repeat=3):
        p[i * 9 + j * 3 + k, i * 9 + j * 3 + k] += 0.5
        p[i * 9 + j * 3 + k, i * 9 + k * 3 + j] += 0.5
    return p


def invariant_dimension(group: list[np.ndarray], rank: int) -> int:
    """Dimension of the ``group``-invariant subspace of the rank-1 or piezoelectric rank-3 space."""
    if rank == 1:
        average = sum(group, np.zeros((3, 3))) / len(group)
        return round(float(np.trace(average)))
    if rank == 3:
        average = sum((np.kron(np.kron(g, g), g) for g in group), np.zeros((27, 27))) / len(group)
        return round(float(np.trace(average @ _strain_symmetric_projector())))
    raise ValueError(f"unsupported rank {rank}; expected 1 or 3")


def parity_gap(proper_subgroup: str, rank: int) -> int:
    """Parity gap ``gamma_r`` of the centrosymmetric class whose proper subgroup is given."""
    return invariant_dimension(close_group(PROPER_GENERATORS[proper_subgroup]), rank)


def parity_gap_rows() -> list[dict[str, str | int]]:
    """The parity-gap table: one row per centrosymmetric class."""
    return [
        {
            "point_group": c.point_group,
            "proper_subgroup": c.proper_subgroup,
            "crystal_system": c.crystal_system,
            "gap_rank1_polarization": parity_gap(c.proper_subgroup, 1),
            "gap_rank3_piezoelectric": parity_gap(c.proper_subgroup, 3),
        }
        for c in CENTROSYMMETRIC_CLASSES
    ]


def check_parity_gap_record(path: Path) -> list[str]:
    """Compare a released parity-gap CSV with the computed table; return mismatch messages."""
    with path.open(newline="") as fh:
        released = list(csv.DictReader(fh))
    computed = parity_gap_rows()
    if len(released) != len(computed):
        return [f"{path.name}: {len(released)} rows, expected {len(computed)}"]
    return [
        f"{path.name}: {want['point_group']} {key} = {got[key]}, computed {want[key]}"
        for got, want in zip(released, computed, strict=True)
        for key in want
        if str(got[key]) != str(want[key])
    ]
